# Generated by Django 4.1.2 on 2022-10-08 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EMP_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('hired_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='inventory_pics')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_type', models.TextField()),
                ('stock_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_address', models.CharField(max_length=100)),
                ('Company_Name', models.CharField(max_length=100)),
                ('Net_TERMS', models.IntegerField()),
                ('Date_Contracted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrders',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('shipped_date', models.DateField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontstore.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoices',
            fields=[
                ('invoice_number', models.IntegerField(primary_key=True, serialize=False)),
                ('DISCOUNT', models.FloatField()),
                ('Invoice_Date', models.DateField()),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontstore.customers')),
                ('EMP_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontstore.employees')),
                ('Order_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontstore.saleorders')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('PO_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('Purchase_date', models.DateField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontstore.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoices',
            fields=[
                ('Purchase_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Amount', models.FloatField()),
                ('Purchase_Date', models.DateField()),
                ('PO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontstore.purchaseorders')),
                ('Supplier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontstore.suppliers')),
            ],
        ),
    ]
